# pair\config\robot_count.yaml
robot_count: 15

waypoints:
  - [0.0, 0.0]
  - [0.5, 0.0]
  - [-0.5, 0.0]
  # - [0.0, 0.5]
  # - [0.0, -0.5]
  # - [0.35, 0.35]
  # - [-0.35, 0.35]
  # - [0.35, -0.35]
  # - [-0.35, -0.35]